### PR TITLE
T55 google analytics

### PR DESCRIPTION
**Pull request by lwrubel**
To test, configure the .env file with the Google Analytics code for the dev environment (see deployment notes). Confirm in GA that views are being registered.

Because this branch also reconfigures the consent footer, confirm that it still is working properly.

### CODE REVIEW

**Comment by kerchner** [comment]
@lwrubel just confirming that it's okay that we're not passing analytics down to the page level.  For example, it's not recording clicks on Help, Citing, Statistics, etc. differently.  Also doesn't seem to be capturing operating system and device info.

image

**Comment by lwrubel** [comment]
I'm seeing user agent and page info in Google Analytics. I'm wondering if it's because there's a lag until that info shows up in GA-- it's not immediate beyond the Realtime info? 

Screen Shot 2021-01-19 at 8 51 41 AM
Screen Shot 2021-01-19 at 8 51 22 AM

**Comment by lwrubel** [comment]
I'm seeing user agent and page info in Google Analytics. I'm wondering if it's because there's a lag until that info shows up in GA-- it's not immediate beyond the Realtime info? 

Screen Shot 2021-01-19 at 8 51 41 AM
Screen Shot 2021-01-19 at 8 51 22 AM

**Comment by kerchner** [comment]
@lwrubel Looks like this needs a rebase w/resolving merge conflicts.

I'm also still having trouble producing a response in Google Analytics.

**Pull request merged**
